import type { Metadata } from "next";
import "./globals.css";
import HotelListPage from "@/components/HotelListPage";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <HotelListPage/>
      </body>
    </html>
  );
}
